// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class CodeCategoryConfiguration : IEntityTypeConfiguration<CodeCategory>
    {
        public void Configure(EntityTypeBuilder<CodeCategory> entity)
        {
            entity.ToTable("CodeCategory");

            entity.Property(e => e.CodeCategoryId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CodeCategory> entity);
    }
}
