// <auto-generated> This file has been generated by Gccg on 2023-09-21 오전 5:42:19. </auto-generated>
#region using
using Chinook.Data;
using Microsoft.AspNetCore.Mvc;
#endregion

namespace Chinook.WebApi.Controllers;


public partial class InvoiceController
{
}

