// <auto-generated> This file has been generated by Gccg</auto-generated>

#region usings
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.Extensions.Logging;
#endregion

namespace Chinook.Data;

#region IEntity
public partial interface IEntity
{
}
#endregion IEntity

#region Untyped Entity
public abstract partial class UntypedEntity : IEntity
{
	[NotMapped]
	[JsonIgnore]
	public object EntityTag { get; set; }

	public void Clear()
	{
		Clear(string.Empty, DateTime.Today);
	}

	public void Clear(DateTime defaultDateTime)
	{
		Clear(string.Empty, defaultDateTime);
	}

	public void Clear(string defaultString, DateTime defaultDateTime)
	{
		Type type = GetType();
		PropertyInfo[] propertyInfoArray = type.GetProperties(BindingFlags.Instance | BindingFlags.Public);

		foreach (PropertyInfo propertyInfo in propertyInfoArray)
		{
			if (propertyInfo.CanWrite == false)
				continue;

			if (propertyInfo.PropertyType == typeof (string))
				propertyInfo.SetValue(this, defaultString, null);

			else if (propertyInfo.PropertyType == typeof (DateTime))
				propertyInfo.SetValue(this, defaultDateTime, null);
		}
	}

	[JsonIgnore]
	public abstract string PrimaryKeyValues {get;}

	[JsonIgnore]
	public abstract string EntityText { get; }

	public abstract string GetEntityTypeName();

	partial void IsLogWritable(ref bool? logWritable);

	[JsonIgnore]
	public virtual bool LogWritable
	{
		get
		{
		bool? logWritable = null;
		IsLogWritable(ref logWritable);

		if (logWritable.HasValue)
			return logWritable.Value;

		return false;
		}
	}

	public virtual string ToEntityLog()
	{
		const int MaxLength = 2000; // 최대 2000자 까지만 저장.

		Type type = GetType();

		var propertyInfoes = type.GetProperties();

		StringBuilder builder = new StringBuilder(ToString());

		builder.AppendLine();
		foreach (var propertyInfo in propertyInfoes)
		{
			if (propertyInfo.PropertyType != typeof (int))
				continue;

			if (propertyInfo.Name.EndsWith("Code") == false)
				continue;

			string textPropertyName = propertyInfo.Name.Substring(0, propertyInfo.Name.Length - 4) + "Text";
			string textValue = GetTextFromCodeProperty(this, type, textPropertyName);

			if (textValue != null)
				builder.AppendFormat("[{0}] {1}{2}", textPropertyName, textValue, Environment.NewLine);
		}

		if (builder.Length > MaxLength)
			return builder.ToString(0, MaxLength);
		else
			return builder.ToString();
	}

	private static string GetTextFromCodeProperty(object entity, Type objectType, string textPropertyName)
	{
		var propertyInfo = objectType.GetProperty(textPropertyName);
		object propertyValue = propertyInfo.GetValue(entity, null);

		if (propertyValue is string)
			return (string) propertyValue;
		else
			return null;
	}
	
	public abstract void ClearKeyValues();
}
#endregion Untyped Entity

#region Entity<T>
public abstract partial class Entity<T> : UntypedEntity, IEditableObject where T : class, new()
{
	public abstract T Clone();

	#region Implementation of IEditableObject

	protected T _clone = null;

	public void BeginEdit()
	{
		if (_clone == null)
			_clone = Clone();
	}

	public void EndEdit()
	{
		_clone = null;
	}

	public abstract void CancelEdit();

	#endregion

	protected internal virtual partial void WriteAuditInfo();
}

#endregion Entity<T>

#region PropertyChangedEventArgs
internal class PropertyChangedEventArgs<T> : EventArgs where T : Entity<T>, new()
{
	/// <summary>
	/// 속성 값이 변경된 엔티티
	/// </summary>
	public T Entity { get; set; }

	public PropertyChangedEventArgs(T entity)
	{
		Entity = entity;
	}
}

internal class PropertyChangingEventArgs<T, K> : EventArgs where T : Entity<T>, new()
{
	public T Entity { get; set; }

	public K Value { get; set; }

	public PropertyChangingEventArgs(T entity, K value)
	{
		Entity = entity;
		Value = value;
	}
}
#endregion PropertyChangedEventArgs

#region Types
public enum LogType
{
	/// <summary>
	/// 엔티티 삽입
	/// </summary>
	Insert,
	/// <summary>
	/// 엔티티 갱신
	/// </summary>
	Update,
	/// <summary>
	/// 엔티티 삭제
	/// </summary>
	Delete
}
#endregion LogType

#region Dao
public partial class DaoBase
{
}

public partial class Dao : DaoBase
{
	static Dao()
	{
		 Album = new AlbumDao(); 
 Artist = new ArtistDao(); 
 Code = new CodeDao(); 
 CodeCategory = new CodeCategoryDao(); 
 Customer = new CustomerDao(); 
 DateTable = new DateTableDao(); 
 Employee = new EmployeeDao(); 
 Genre = new GenreDao(); 
 Invoice = new InvoiceDao(); 
 InvoiceLine = new InvoiceLineDao(); 
 MediaType = new MediaTypeDao(); 
 Playlist = new PlaylistDao(); 
 PlaylistTrack = new PlaylistTrackDao(); 
 PlaylistTrackHistory = new PlaylistTrackHistoryDao(); 
 TimeTable = new TimeTableDao(); 
 Track = new TrackDao(); 

	}

	#region Data objects
	 public static AlbumDao Album { get; } 
 public static ArtistDao Artist { get; } 
 public static CodeDao Code { get; } 
 public static CodeCategoryDao CodeCategory { get; } 
 public static CustomerDao Customer { get; } 
 public static DateTableDao DateTable { get; } 
 public static EmployeeDao Employee { get; } 
 public static GenreDao Genre { get; } 
 public static InvoiceDao Invoice { get; } 
 public static InvoiceLineDao InvoiceLine { get; } 
 public static MediaTypeDao MediaType { get; } 
 public static PlaylistDao Playlist { get; } 
 public static PlaylistTrackDao PlaylistTrack { get; } 
 public static PlaylistTrackHistoryDao PlaylistTrackHistory { get; } 
 public static TimeTableDao TimeTable { get; } 
 public static TrackDao Track { get; } 

	#endregion

	public static EntityDao<T> Get<T>() where T : Entity<T>, new()
    {
        object result = typeof(T).Name switch
        {
             "Album" => Album, 
 "Artist" => Artist, 
 "Code" => Code, 
 "CodeCategory" => CodeCategory, 
 "Customer" => Customer, 
 "DateTable" => DateTable, 
 "Employee" => Employee, 
 "Genre" => Genre, 
 "Invoice" => Invoice, 
 "InvoiceLine" => InvoiceLine, 
 "MediaType" => MediaType, 
 "Playlist" => Playlist, 
 "PlaylistTrack" => PlaylistTrack, 
 "PlaylistTrackHistory" => PlaylistTrackHistory, 
 "TimeTable" => TimeTable, 
 "Track" => Track, 

			_ => throw new NotImplementedException("Dao.Get")
        };

        return result as EntityDao<T>;
    }
}
#endregion

#region ChinookContextLoggerFactory
internal class ChinookContextLoggerFactory : LoggerFactory
{
    #region singleton
    private static ChinookContextLoggerFactory _instance;

    public static ChinookContextLoggerFactory GetInstance(params LogPath[] loggerTypes) => GetInstance(loggerTypes.Select(x => x.ToString()).ToArray());

    public static ChinookContextLoggerFactory GetInstance(params string[] logPathes)
    {
        if (_instance == null)
        {
            List<ILoggerProvider> logProviders = new List<ILoggerProvider>(logPathes.Select(x => new LogProvider(x)));
            _instance = new ChinookContextLoggerFactory(logProviders);
        }

        return _instance;
    }

    private ChinookContextLoggerFactory(List<ILoggerProvider> providers) : base(providers)
    {
    }

    #endregion singleton

    internal class LogProvider : ILoggerProvider
    {
        public LogProvider(string logPath) => _logPath = logPath;

        private string _logPath;

        public void Dispose()
        {
        }

        public ILogger CreateLogger(string categoryName)
        {
            return new Logger(categoryName, _logPath);
        }
    }

    internal class Logger : ILogger
    {
        private readonly IWriter _writer;

        private readonly string _categoryName;

        public Logger(string categoryName, string logPath)
        {
            _categoryName = categoryName;

            _writer = logPath switch
            {
                nameof(LogPath.Console) => new ConsoleWriter(),
                nameof(LogPath.Debug) => new DebugWriter(),
                _ => new FileWriter(logPath),
            };

            if (_counters.ContainsKey(_writer.UniqueName) is false)
                _counters.TryAdd(_writer.UniqueName, 0);
        }

        private static System.Collections.Concurrent.ConcurrentDictionary<string, int> _counters = new();

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
        {
            _writer.Open();
            _writer.WriteLine($"[{_counters[_writer.UniqueName]++:N0}] {DateTime.Now:s}");
            _writer.WriteLine(formatter(state, exception));
            _writer.WriteLine("--------------------------------------------------");
            _writer.WriteLine(Environment.NewLine);
            _writer.Save();
        }

        public bool IsEnabled(LogLevel logLevel)
        {
            return logLevel == LogLevel.Information &&
                    _categoryName == DbLoggerCategory.Database.Command.Name;
        }

        public IDisposable BeginScope<TState>(TState state)
        {
            return null;
        }
    }

    public interface IWriter
    {
        string UniqueName { get; }

        void WriteLine(string format, params object[] args);

        void Open()
        {
        }

        void Save()
        {
        }
    }

    internal class ConsoleWriter : IWriter
    {
        public string UniqueName => nameof(ConsoleWriter);

        public void WriteLine(string format, params object[] args) => Console.WriteLine(format, args);
    }

    internal class DebugWriter : IWriter
    {
        public string UniqueName => nameof(DebugWriter);

        public void WriteLine(string format, params object[] args) => Debug.WriteLine(format, args);
    }

    internal class FileWriter : IWriter
    {
        private readonly string _logFilePath;

        public string UniqueName => _logFilePath;

        public FileWriter(string logFilePath)
        {
            _logFilePath = logFilePath;
        }

        private readonly StringBuilder _builder = new StringBuilder();

        public void WriteLine(string format, params object[] args)
        {
            _builder.AppendFormat(format, args);
            _builder.AppendLine();
        }

        public void Open()
        {
            _builder.Clear();
        }

        public void Save()
        {
            File.AppendAllText(_logFilePath, _builder.ToString());
        }
    }
}

internal enum LogPath
{
    /// <summary>
    /// 콘솔에 출력
    /// </summary>
    Console,
    /// <summary>
    /// 디버거 창에 출력
    /// </summary>
    Debug,
}
#endregion ChinookContextLoggerFactory

#region Entities
 #region Album
public partial class Album : Entity<Album>, IEntity
{
	public const string EntityTypeName = "Album";

	public static void Copy(Album source, Album target)
	{
		target.AlbumId = source.AlbumId; 		
target.ArtistId = source.ArtistId; 		
target.Title = source.Title; 		
target.TypeCode = source.TypeCode; 
	}

	public override Album Clone()
	{
		var clone = new Album();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[AlbumId]" + AlbumId  + ", " + "[ArtistId]" + ArtistId  + ", " + "[Title]" + Title  + ", " + "[TypeCode]" + TypeCode ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", AlbumId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		AlbumId = default;
	}
}

public enum AlbumColumn
{
	AlbumId ,
ArtistId ,
Title ,
TypeCode 
}

public class AlbumEqualityComparer : IEqualityComparer<Album>
{
    #region singleton
    private static readonly Lazy<AlbumEqualityComparer> _instance = new(() => new AlbumEqualityComparer());

    public static AlbumEqualityComparer Instance => _instance.Value;

    private AlbumEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Album x, Album y)
	{
		return x.AlbumId == y.AlbumId ;
	}

	public int GetHashCode(Album obj)
	{
		return obj.AlbumId.GetHashCode() ;
	}
}
#endregion Album

 #region Artist
public partial class Artist : Entity<Artist>, IEntity
{
	public const string EntityTypeName = "Artist";

	public static void Copy(Artist source, Artist target)
	{
		target.ArtistId = source.ArtistId; 		
target.Name = source.Name; 		
target.TypeCode = source.TypeCode; 
	}

	public override Artist Clone()
	{
		var clone = new Artist();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[ArtistId]" + ArtistId  + ", " + "[Name]" + Name  + ", " + "[TypeCode]" + TypeCode ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", ArtistId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		ArtistId = default;
	}
}

public enum ArtistColumn
{
	ArtistId ,
Name ,
TypeCode 
}

public class ArtistEqualityComparer : IEqualityComparer<Artist>
{
    #region singleton
    private static readonly Lazy<ArtistEqualityComparer> _instance = new(() => new ArtistEqualityComparer());

    public static ArtistEqualityComparer Instance => _instance.Value;

    private ArtistEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Artist x, Artist y)
	{
		return x.ArtistId == y.ArtistId ;
	}

	public int GetHashCode(Artist obj)
	{
		return obj.ArtistId.GetHashCode() ;
	}
}
#endregion Artist

 #region Code
public partial class Code : Entity<Code>, IEntity
{
	public const string EntityTypeName = "Code";

	public static void Copy(Code source, Code target)
	{
		target.CodeId = source.CodeId; 		
target.CodeCategoryId = source.CodeCategoryId; 		
target.Memo = source.Memo; 		
target.Text = source.Text; 
	}

	public override Code Clone()
	{
		var clone = new Code();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[CodeId]" + CodeId  + ", " + "[CodeCategoryId]" + CodeCategoryId  + ", " + "[Memo]" + Memo  + ", " + "[Text]" + Text ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", CodeId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		CodeId = default;
	}
}

public enum CodeColumn
{
	CodeId ,
CodeCategoryId ,
Memo ,
Text 
}

public class CodeEqualityComparer : IEqualityComparer<Code>
{
    #region singleton
    private static readonly Lazy<CodeEqualityComparer> _instance = new(() => new CodeEqualityComparer());

    public static CodeEqualityComparer Instance => _instance.Value;

    private CodeEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Code x, Code y)
	{
		return x.CodeId == y.CodeId ;
	}

	public int GetHashCode(Code obj)
	{
		return obj.CodeId.GetHashCode() ;
	}
}
#endregion Code

 #region CodeCategory
public partial class CodeCategory : Entity<CodeCategory>, IEntity
{
	public const string EntityTypeName = "CodeCategory";

	public static void Copy(CodeCategory source, CodeCategory target)
	{
		target.CodeCategoryId = source.CodeCategoryId; 		
target.Name = source.Name; 
	}

	public override CodeCategory Clone()
	{
		var clone = new CodeCategory();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[CodeCategoryId]" + CodeCategoryId  + ", " + "[Name]" + Name ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", CodeCategoryId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		CodeCategoryId = default;
	}
}

public enum CodeCategoryColumn
{
	CodeCategoryId ,
Name 
}

public class CodeCategoryEqualityComparer : IEqualityComparer<CodeCategory>
{
    #region singleton
    private static readonly Lazy<CodeCategoryEqualityComparer> _instance = new(() => new CodeCategoryEqualityComparer());

    public static CodeCategoryEqualityComparer Instance => _instance.Value;

    private CodeCategoryEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(CodeCategory x, CodeCategory y)
	{
		return x.CodeCategoryId == y.CodeCategoryId ;
	}

	public int GetHashCode(CodeCategory obj)
	{
		return obj.CodeCategoryId.GetHashCode() ;
	}
}
#endregion CodeCategory

 #region Customer
public partial class Customer : Entity<Customer>, IEntity
{
	public const string EntityTypeName = "Customer";

	public static void Copy(Customer source, Customer target)
	{
		target.CustomerId = source.CustomerId; 		
target.Address = source.Address; 		
target.City = source.City; 		
target.Company = source.Company; 		
target.Country = source.Country; 		
target.Email = source.Email; 		
target.Fax = source.Fax; 		
target.FirstName = source.FirstName; 		
target.LastName = source.LastName; 		
target.Phone = source.Phone; 		
target.PostalCode = source.PostalCode; 		
target.State = source.State; 		
target.SupportRepId = source.SupportRepId; 
	}

	public override Customer Clone()
	{
		var clone = new Customer();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[CustomerId]" + CustomerId  + ", " + "[Address]" + Address  + ", " + "[City]" + City  + ", " + "[Company]" + Company  + ", " + "[Country]" + Country  + ", " + "[Email]" + Email  + ", " + "[Fax]" + Fax  + ", " + "[FirstName]" + FirstName  + ", " + "[LastName]" + LastName  + ", " + "[Phone]" + Phone  + ", " + "[PostalCode]" + PostalCode  + ", " + "[State]" + State  + ", " + "[SupportRepId]" + SupportRepId ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", CustomerId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		CustomerId = default;
	}
}

public enum CustomerColumn
{
	CustomerId ,
Address ,
City ,
Company ,
Country ,
Email ,
Fax ,
FirstName ,
LastName ,
Phone ,
PostalCode ,
State ,
SupportRepId 
}

public class CustomerEqualityComparer : IEqualityComparer<Customer>
{
    #region singleton
    private static readonly Lazy<CustomerEqualityComparer> _instance = new(() => new CustomerEqualityComparer());

    public static CustomerEqualityComparer Instance => _instance.Value;

    private CustomerEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Customer x, Customer y)
	{
		return x.CustomerId == y.CustomerId ;
	}

	public int GetHashCode(Customer obj)
	{
		return obj.CustomerId.GetHashCode() ;
	}
}
#endregion Customer

 #region DateTable
public partial class DateTable : Entity<DateTable>, IEntity
{
	public const string EntityTypeName = "DateTable";

	public static void Copy(DateTable source, DateTable target)
	{
		target.Date = source.Date; 		
target.DateNull = source.DateNull; 
	}

	public override DateTable Clone()
	{
		var clone = new DateTable();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[Date]" + Date  + ", " + "[DateNull]" + DateNull ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", Date ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		Date = default;
	}
}

public enum DateTableColumn
{
	Date ,
DateNull 
}

public class DateTableEqualityComparer : IEqualityComparer<DateTable>
{
    #region singleton
    private static readonly Lazy<DateTableEqualityComparer> _instance = new(() => new DateTableEqualityComparer());

    public static DateTableEqualityComparer Instance => _instance.Value;

    private DateTableEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(DateTable x, DateTable y)
	{
		return x.Date == y.Date ;
	}

	public int GetHashCode(DateTable obj)
	{
		return obj.Date.GetHashCode() ;
	}
}
#endregion DateTable

 #region Employee
public partial class Employee : Entity<Employee>, IEntity
{
	public const string EntityTypeName = "Employee";

	public static void Copy(Employee source, Employee target)
	{
		target.EmployeeId = source.EmployeeId; 		
target.Address = source.Address; 		
target.BirthDate = source.BirthDate; 		
target.City = source.City; 		
target.Country = source.Country; 		
target.Email = source.Email; 		
target.Fax = source.Fax; 		
target.FirstName = source.FirstName; 		
target.HireDate = source.HireDate; 		
target.LastName = source.LastName; 		
target.Phone = source.Phone; 		
target.PostalCode = source.PostalCode; 		
target.ReportsTo = source.ReportsTo; 		
target.State = source.State; 		
target.Title = source.Title; 
	}

	public override Employee Clone()
	{
		var clone = new Employee();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[EmployeeId]" + EmployeeId  + ", " + "[Address]" + Address  + ", " + "[BirthDate]" + BirthDate  + ", " + "[City]" + City  + ", " + "[Country]" + Country  + ", " + "[Email]" + Email  + ", " + "[Fax]" + Fax  + ", " + "[FirstName]" + FirstName  + ", " + "[HireDate]" + HireDate  + ", " + "[LastName]" + LastName  + ", " + "[Phone]" + Phone  + ", " + "[PostalCode]" + PostalCode  + ", " + "[ReportsTo]" + ReportsTo  + ", " + "[State]" + State  + ", " + "[Title]" + Title ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", EmployeeId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		EmployeeId = default;
	}
}

public enum EmployeeColumn
{
	EmployeeId ,
Address ,
BirthDate ,
City ,
Country ,
Email ,
Fax ,
FirstName ,
HireDate ,
LastName ,
Phone ,
PostalCode ,
ReportsTo ,
State ,
Title 
}

public class EmployeeEqualityComparer : IEqualityComparer<Employee>
{
    #region singleton
    private static readonly Lazy<EmployeeEqualityComparer> _instance = new(() => new EmployeeEqualityComparer());

    public static EmployeeEqualityComparer Instance => _instance.Value;

    private EmployeeEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Employee x, Employee y)
	{
		return x.EmployeeId == y.EmployeeId ;
	}

	public int GetHashCode(Employee obj)
	{
		return obj.EmployeeId.GetHashCode() ;
	}
}
#endregion Employee

 #region Genre
public partial class Genre : Entity<Genre>, IEntity
{
	public const string EntityTypeName = "Genre";

	public static void Copy(Genre source, Genre target)
	{
		target.GenreId = source.GenreId; 		
target.Name = source.Name; 
	}

	public override Genre Clone()
	{
		var clone = new Genre();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[GenreId]" + GenreId  + ", " + "[Name]" + Name ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", GenreId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		GenreId = default;
	}
}

public enum GenreColumn
{
	GenreId ,
Name 
}

public class GenreEqualityComparer : IEqualityComparer<Genre>
{
    #region singleton
    private static readonly Lazy<GenreEqualityComparer> _instance = new(() => new GenreEqualityComparer());

    public static GenreEqualityComparer Instance => _instance.Value;

    private GenreEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Genre x, Genre y)
	{
		return x.GenreId == y.GenreId ;
	}

	public int GetHashCode(Genre obj)
	{
		return obj.GenreId.GetHashCode() ;
	}
}
#endregion Genre

 #region Invoice
public partial class Invoice : Entity<Invoice>, IEntity
{
	public const string EntityTypeName = "Invoice";

	public static void Copy(Invoice source, Invoice target)
	{
		target.InvoiceId = source.InvoiceId; 		
target.BillingAddress = source.BillingAddress; 		
target.BillingCity = source.BillingCity; 		
target.BillingCountry = source.BillingCountry; 		
target.BillingPostalCode = source.BillingPostalCode; 		
target.BillingState = source.BillingState; 		
target.CustomerId = source.CustomerId; 		
target.InvoiceDate = source.InvoiceDate; 		
target.Total = source.Total; 
	}

	public override Invoice Clone()
	{
		var clone = new Invoice();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[InvoiceId]" + InvoiceId  + ", " + "[BillingAddress]" + BillingAddress  + ", " + "[BillingCity]" + BillingCity  + ", " + "[BillingCountry]" + BillingCountry  + ", " + "[BillingPostalCode]" + BillingPostalCode  + ", " + "[BillingState]" + BillingState  + ", " + "[CustomerId]" + CustomerId  + ", " + "[InvoiceDate]" + InvoiceDate  + ", " + "[Total]" + Total ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", InvoiceId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		InvoiceId = default;
	}
}

public enum InvoiceColumn
{
	InvoiceId ,
BillingAddress ,
BillingCity ,
BillingCountry ,
BillingPostalCode ,
BillingState ,
CustomerId ,
InvoiceDate ,
Total 
}

public class InvoiceEqualityComparer : IEqualityComparer<Invoice>
{
    #region singleton
    private static readonly Lazy<InvoiceEqualityComparer> _instance = new(() => new InvoiceEqualityComparer());

    public static InvoiceEqualityComparer Instance => _instance.Value;

    private InvoiceEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Invoice x, Invoice y)
	{
		return x.InvoiceId == y.InvoiceId ;
	}

	public int GetHashCode(Invoice obj)
	{
		return obj.InvoiceId.GetHashCode() ;
	}
}
#endregion Invoice

 #region InvoiceLine
public partial class InvoiceLine : Entity<InvoiceLine>, IEntity
{
	public const string EntityTypeName = "InvoiceLine";

	public static void Copy(InvoiceLine source, InvoiceLine target)
	{
		target.InvoiceLineId = source.InvoiceLineId; 		
target.InvoiceId = source.InvoiceId; 		
target.Quantity = source.Quantity; 		
target.TrackId = source.TrackId; 		
target.UnitPrice = source.UnitPrice; 
	}

	public override InvoiceLine Clone()
	{
		var clone = new InvoiceLine();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[InvoiceLineId]" + InvoiceLineId  + ", " + "[InvoiceId]" + InvoiceId  + ", " + "[Quantity]" + Quantity  + ", " + "[TrackId]" + TrackId  + ", " + "[UnitPrice]" + UnitPrice ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", InvoiceLineId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		InvoiceLineId = default;
	}
}

public enum InvoiceLineColumn
{
	InvoiceLineId ,
InvoiceId ,
Quantity ,
TrackId ,
UnitPrice 
}

public class InvoiceLineEqualityComparer : IEqualityComparer<InvoiceLine>
{
    #region singleton
    private static readonly Lazy<InvoiceLineEqualityComparer> _instance = new(() => new InvoiceLineEqualityComparer());

    public static InvoiceLineEqualityComparer Instance => _instance.Value;

    private InvoiceLineEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(InvoiceLine x, InvoiceLine y)
	{
		return x.InvoiceLineId == y.InvoiceLineId ;
	}

	public int GetHashCode(InvoiceLine obj)
	{
		return obj.InvoiceLineId.GetHashCode() ;
	}
}
#endregion InvoiceLine

 #region MediaType
public partial class MediaType : Entity<MediaType>, IEntity
{
	public const string EntityTypeName = "MediaType";

	public static void Copy(MediaType source, MediaType target)
	{
		target.MediaTypeId = source.MediaTypeId; 		
target.Name = source.Name; 
	}

	public override MediaType Clone()
	{
		var clone = new MediaType();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[MediaTypeId]" + MediaTypeId  + ", " + "[Name]" + Name ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", MediaTypeId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		MediaTypeId = default;
	}
}

public enum MediaTypeColumn
{
	MediaTypeId ,
Name 
}

public class MediaTypeEqualityComparer : IEqualityComparer<MediaType>
{
    #region singleton
    private static readonly Lazy<MediaTypeEqualityComparer> _instance = new(() => new MediaTypeEqualityComparer());

    public static MediaTypeEqualityComparer Instance => _instance.Value;

    private MediaTypeEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(MediaType x, MediaType y)
	{
		return x.MediaTypeId == y.MediaTypeId ;
	}

	public int GetHashCode(MediaType obj)
	{
		return obj.MediaTypeId.GetHashCode() ;
	}
}
#endregion MediaType

 #region Playlist
public partial class Playlist : Entity<Playlist>, IEntity
{
	public const string EntityTypeName = "Playlist";

	public static void Copy(Playlist source, Playlist target)
	{
		target.PlaylistId = source.PlaylistId; 		
target.Name = source.Name; 
	}

	public override Playlist Clone()
	{
		var clone = new Playlist();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[PlaylistId]" + PlaylistId  + ", " + "[Name]" + Name ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", PlaylistId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		PlaylistId = default;
	}
}

public enum PlaylistColumn
{
	PlaylistId ,
Name 
}

public class PlaylistEqualityComparer : IEqualityComparer<Playlist>
{
    #region singleton
    private static readonly Lazy<PlaylistEqualityComparer> _instance = new(() => new PlaylistEqualityComparer());

    public static PlaylistEqualityComparer Instance => _instance.Value;

    private PlaylistEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Playlist x, Playlist y)
	{
		return x.PlaylistId == y.PlaylistId ;
	}

	public int GetHashCode(Playlist obj)
	{
		return obj.PlaylistId.GetHashCode() ;
	}
}
#endregion Playlist

 #region PlaylistTrack
public partial class PlaylistTrack : Entity<PlaylistTrack>, IEntity
{
	public const string EntityTypeName = "PlaylistTrack";

	public static void Copy(PlaylistTrack source, PlaylistTrack target)
	{
		target.PlaylistId = source.PlaylistId; 		
target.TrackId = source.TrackId; 
	}

	public override PlaylistTrack Clone()
	{
		var clone = new PlaylistTrack();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[PlaylistId]" + PlaylistId  + ", " + "[TrackId]" + TrackId ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", PlaylistId , TrackId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		PlaylistId = default;
TrackId = default;
	}
}

public enum PlaylistTrackColumn
{
	PlaylistId ,
TrackId 
}

public class PlaylistTrackEqualityComparer : IEqualityComparer<PlaylistTrack>
{
    #region singleton
    private static readonly Lazy<PlaylistTrackEqualityComparer> _instance = new(() => new PlaylistTrackEqualityComparer());

    public static PlaylistTrackEqualityComparer Instance => _instance.Value;

    private PlaylistTrackEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(PlaylistTrack x, PlaylistTrack y)
	{
		return x.PlaylistId == y.PlaylistId  && x.TrackId == y.TrackId ;
	}

	public int GetHashCode(PlaylistTrack obj)
	{
		return obj.PlaylistId.GetHashCode()  ^ obj.TrackId.GetHashCode() ;
	}
}
#endregion PlaylistTrack

 #region PlaylistTrackHistory
public partial class PlaylistTrackHistory : Entity<PlaylistTrackHistory>, IEntity
{
	public const string EntityTypeName = "PlaylistTrackHistory";

	public static void Copy(PlaylistTrackHistory source, PlaylistTrackHistory target)
	{
		target.PlaylistId = source.PlaylistId; 		
target.TrackId = source.TrackId; 		
target.WrittenAt = source.WrittenAt; 		
target.Memo = source.Memo; 
	}

	public override PlaylistTrackHistory Clone()
	{
		var clone = new PlaylistTrackHistory();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[PlaylistId]" + PlaylistId  + ", " + "[TrackId]" + TrackId  + ", " + "[WrittenAt]" + WrittenAt  + ", " + "[Memo]" + Memo ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", PlaylistId , TrackId , WrittenAt ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		PlaylistId = default;
TrackId = default;
WrittenAt = default;
	}
}

public enum PlaylistTrackHistoryColumn
{
	PlaylistId ,
TrackId ,
WrittenAt ,
Memo 
}

public class PlaylistTrackHistoryEqualityComparer : IEqualityComparer<PlaylistTrackHistory>
{
    #region singleton
    private static readonly Lazy<PlaylistTrackHistoryEqualityComparer> _instance = new(() => new PlaylistTrackHistoryEqualityComparer());

    public static PlaylistTrackHistoryEqualityComparer Instance => _instance.Value;

    private PlaylistTrackHistoryEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(PlaylistTrackHistory x, PlaylistTrackHistory y)
	{
		return x.PlaylistId == y.PlaylistId  && x.TrackId == y.TrackId  && x.WrittenAt == y.WrittenAt ;
	}

	public int GetHashCode(PlaylistTrackHistory obj)
	{
		return obj.PlaylistId.GetHashCode()  ^ obj.TrackId.GetHashCode()  ^ obj.WrittenAt.GetHashCode() ;
	}
}
#endregion PlaylistTrackHistory

 #region TimeTable
public partial class TimeTable : Entity<TimeTable>, IEntity
{
	public const string EntityTypeName = "TimeTable";

	public static void Copy(TimeTable source, TimeTable target)
	{
		target.Time = source.Time; 		
target.TimeNull = source.TimeNull; 
	}

	public override TimeTable Clone()
	{
		var clone = new TimeTable();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[Time]" + Time  + ", " + "[TimeNull]" + TimeNull ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", Time ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		Time = default;
	}
}

public enum TimeTableColumn
{
	Time ,
TimeNull 
}

public class TimeTableEqualityComparer : IEqualityComparer<TimeTable>
{
    #region singleton
    private static readonly Lazy<TimeTableEqualityComparer> _instance = new(() => new TimeTableEqualityComparer());

    public static TimeTableEqualityComparer Instance => _instance.Value;

    private TimeTableEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(TimeTable x, TimeTable y)
	{
		return x.Time == y.Time ;
	}

	public int GetHashCode(TimeTable obj)
	{
		return obj.Time.GetHashCode() ;
	}
}
#endregion TimeTable

 #region Track
public partial class Track : Entity<Track>, IEntity
{
	public const string EntityTypeName = "Track";

	public static void Copy(Track source, Track target)
	{
		target.TrackId = source.TrackId; 		
target.AlbumId = source.AlbumId; 		
target.BigIntCol = source.BigIntCol; 		
target.BigIntColNull = source.BigIntColNull; 		
target.BinaryCol = source.BinaryCol; 		
target.BinaryColNull = source.BinaryColNull; 		
target.BitCol = source.BitCol; 		
target.BitColNull = source.BitColNull; 		
target.CharCol = source.CharCol; 		
target.CharColNull = source.CharColNull; 		
target.DateCol = source.DateCol; 		
target.DateColNull = source.DateColNull; 		
target.DateOnlyCol = source.DateOnlyCol; 		
target.DateOnlyColNull = source.DateOnlyColNull; 		
target.DateTimeCol = source.DateTimeCol; 		
target.DateTimeColNull = source.DateTimeColNull; 		
target.DecimalCol = source.DecimalCol; 		
target.DecimalColNull = source.DecimalColNull; 		
target.FloatCol = source.FloatCol; 		
target.FloatColNull = source.FloatColNull; 		
target.GenreId = source.GenreId; 		
target.GuidCol = source.GuidCol; 		
target.GuidColNull = source.GuidColNull; 		
target.MediaTypeId = source.MediaTypeId; 		
target.Name = source.Name; 		
target.NcharCol = source.NcharCol; 		
target.NcharColNull = source.NcharColNull; 		
target.NvarCharCol = source.NvarCharCol; 		
target.NvarCharColNull = source.NvarCharColNull; 		
target.RealCol = source.RealCol; 		
target.RealColNull = source.RealColNull; 		
target.SmallDateTimeCol = source.SmallDateTimeCol; 		
target.SmallDateTimeColNull = source.SmallDateTimeColNull; 		
target.SmallIntCol = source.SmallIntCol; 		
target.SmallIntColNull = source.SmallIntColNull; 		
target.SmallMoneyCol = source.SmallMoneyCol; 		
target.SmallMoneyColNull = source.SmallMoneyColNull; 		
target.TimeCol = source.TimeCol; 		
target.TimeColNull = source.TimeColNull; 		
target.TimeOnlyCol = source.TimeOnlyCol; 		
target.TimeOnlyColNull = source.TimeOnlyColNull; 		
target.TimestampCol = source.TimestampCol; 		
target.TinyIntCol = source.TinyIntCol; 		
target.TinyIntColNull = source.TinyIntColNull; 		
target.VarBinaryCol = source.VarBinaryCol; 		
target.VarBinaryColNull = source.VarBinaryColNull; 		
target.VarCharCol = source.VarCharCol; 		
target.VarCharColNull = source.VarCharColNull; 
	}

	public override Track Clone()
	{
		var clone = new Track();

		Copy(this, clone);

		return clone;
	}
	partial void GetEntityTextCore(ref string value);

	[JsonIgnore]
	public override string EntityText
	{
		get 
		{ 
			string value = null;
			GetEntityTextCore(ref value);

			if (value != null)
				return value;

			return PrimaryKeyValues; 
		}
	}

	partial void ToStringCore(ref string value);

	public override string ToString()
	{
		string value = null;
		ToStringCore(ref value);

		if (value != null)
			return value;

		return "[TrackId]" + TrackId  + ", " + "[AlbumId]" + AlbumId  + ", " + "[BigIntCol]" + BigIntCol  + ", " + "[BigIntColNull]" + BigIntColNull  + ", " + "[BinaryCol]" + BinaryCol  + ", " + "[BinaryColNull]" + BinaryColNull  + ", " + "[BitCol]" + BitCol  + ", " + "[BitColNull]" + BitColNull  + ", " + "[CharCol]" + CharCol  + ", " + "[CharColNull]" + CharColNull  + ", " + "[DateCol]" + DateCol  + ", " + "[DateColNull]" + DateColNull  + ", " + "[DateOnlyCol]" + DateOnlyCol  + ", " + "[DateOnlyColNull]" + DateOnlyColNull  + ", " + "[DateTimeCol]" + DateTimeCol  + ", " + "[DateTimeColNull]" + DateTimeColNull  + ", " + "[DecimalCol]" + DecimalCol  + ", " + "[DecimalColNull]" + DecimalColNull  + ", " + "[FloatCol]" + FloatCol  + ", " + "[FloatColNull]" + FloatColNull  + ", " + "[GenreId]" + GenreId  + ", " + "[GuidCol]" + GuidCol  + ", " + "[GuidColNull]" + GuidColNull  + ", " + "[MediaTypeId]" + MediaTypeId  + ", " + "[Name]" + Name  + ", " + "[NcharCol]" + NcharCol  + ", " + "[NcharColNull]" + NcharColNull  + ", " + "[NvarCharCol]" + NvarCharCol  + ", " + "[NvarCharColNull]" + NvarCharColNull  + ", " + "[RealCol]" + RealCol  + ", " + "[RealColNull]" + RealColNull  + ", " + "[SmallDateTimeCol]" + SmallDateTimeCol  + ", " + "[SmallDateTimeColNull]" + SmallDateTimeColNull  + ", " + "[SmallIntCol]" + SmallIntCol  + ", " + "[SmallIntColNull]" + SmallIntColNull  + ", " + "[SmallMoneyCol]" + SmallMoneyCol  + ", " + "[SmallMoneyColNull]" + SmallMoneyColNull  + ", " + "[TimeCol]" + TimeCol  + ", " + "[TimeColNull]" + TimeColNull  + ", " + "[TimeOnlyCol]" + TimeOnlyCol  + ", " + "[TimeOnlyColNull]" + TimeOnlyColNull  + ", " + "[TimestampCol]" + TimestampCol  + ", " + "[TinyIntCol]" + TinyIntCol  + ", " + "[TinyIntColNull]" + TinyIntColNull  + ", " + "[VarBinaryCol]" + VarBinaryCol  + ", " + "[VarBinaryColNull]" + VarBinaryColNull  + ", " + "[VarCharCol]" + VarCharCol  + ", " + "[VarCharColNull]" + VarCharColNull ;
	}

	public override void CancelEdit()
	{
		if (_clone != null)
			Copy(_clone, this);
	}

	[JsonIgnore]
	public override string PrimaryKeyValues
	{
		get { return string.Join(":", TrackId ); }
	}

	public override string GetEntityTypeName()
	{
		return EntityTypeName;
	}

    partial void ClearKeyValuesCore(ref bool handled);

	public override void ClearKeyValues()
	{
        bool handled = false;
		ClearKeyValuesCore(ref handled);
		if (handled)
			return;

		TrackId = default;
	}
}

public enum TrackColumn
{
	TrackId ,
AlbumId ,
BigIntCol ,
BigIntColNull ,
BinaryCol ,
BinaryColNull ,
BitCol ,
BitColNull ,
CharCol ,
CharColNull ,
DateCol ,
DateColNull ,
DateOnlyCol ,
DateOnlyColNull ,
DateTimeCol ,
DateTimeColNull ,
DecimalCol ,
DecimalColNull ,
FloatCol ,
FloatColNull ,
GenreId ,
GuidCol ,
GuidColNull ,
MediaTypeId ,
Name ,
NcharCol ,
NcharColNull ,
NvarCharCol ,
NvarCharColNull ,
RealCol ,
RealColNull ,
SmallDateTimeCol ,
SmallDateTimeColNull ,
SmallIntCol ,
SmallIntColNull ,
SmallMoneyCol ,
SmallMoneyColNull ,
TimeCol ,
TimeColNull ,
TimeOnlyCol ,
TimeOnlyColNull ,
TimestampCol ,
TinyIntCol ,
TinyIntColNull ,
VarBinaryCol ,
VarBinaryColNull ,
VarCharCol ,
VarCharColNull 
}

public class TrackEqualityComparer : IEqualityComparer<Track>
{
    #region singleton
    private static readonly Lazy<TrackEqualityComparer> _instance = new(() => new TrackEqualityComparer());

    public static TrackEqualityComparer Instance => _instance.Value;

    private TrackEqualityComparer()
    {
    }
    #endregion singleton

	public bool Equals(Track x, Track y)
	{
		return x.TrackId == y.TrackId ;
	}

	public int GetHashCode(Track obj)
	{
		return obj.TrackId.GetHashCode() ;
	}
}
#endregion Track


#endregion Entities

#region EntityDao<T>
public abstract partial class EntityDao<T> where T : Entity<T>, new()
{
	internal EntityDao() { }

	#region Create
	public virtual T Create()
	{
		return Create(string.Empty, DateTime.Today);
	}

	public virtual T Create(DateTime defaultDateTime)
	{
		return Create(string.Empty, defaultDateTime);
	}

	public virtual T Create(string defaultString, DateTime defaultDateTime)
	{
		T entity = new T();
		entity.Clear(defaultString, defaultDateTime);

		return entity;
	}
	#endregion Create

	protected abstract Expression<Func<T, bool>> HasSameKey(T other);

	#region Write log partial methods
	protected virtual partial void OnSaving(T entity, LogType logType);

	protected virtual partial void OnSaved(T entity, LogType logType);
	#endregion Write log partial methods

    private IQueryable<T> MakeCountQuery(Expression<Func<T, bool>> where, DbContext context)
    {
        var query = from item in context.Set<T>()
            select item;

        if (where != null)
            query = query.Where(where);

        return query;
    }

	private static IQueryable<T> GetListCore<O>(Expression<Func<T, bool>> where, Expression<Func<T, O>> orderBy, bool ascending, int startRowIndex, int maximumRows, DbContext context)
	{
		var query = from x in context.Set<T>()
					select x;

		if (where != null)
			query = query.Where(where);

		IOrderedQueryable<T> orderedQuery = null;

		if (orderBy != null)
			orderedQuery = (ascending) ? query.OrderBy(orderBy) : query.OrderByDescending(orderBy);

		if (startRowIndex != 0 || maximumRows != int.MaxValue)
		{
			if (orderedQuery != null)
				orderedQuery = (IOrderedQueryable<T>)orderedQuery.Skip(startRowIndex).Take(maximumRows);
			else
				query = query.Skip(startRowIndex).Take(maximumRows);
		}

		return orderedQuery ?? query;
	}

    private static IQueryable<T> GetScalarCore<O>(Expression<Func<T, bool>> where, Expression<Func<T, O>> orderBy, bool ascending, DbContext context)
	{
		var query = from x in context.Set<T>()
					select x;

		if (where != null)
			query = query.Where(where);

        // 마지막 행은 orderby가 반드시 지정되어 있어야 함. orderby를 지정하지 않으면 skip 메서드를 사용할 수 없기 때문.
        if (orderBy != null)
			query = @ascending ? query.OrderBy(orderBy) : query.OrderByDescending(orderBy);

        return query;
	}

    internal virtual void MarkToSave(DbContext context, LogType logType, T entity)
    {
        OnSaving(entity, logType);

        context.Entry(entity).State = logType switch
        {
            LogType.Insert => EntityState.Added,
            LogType.Update => EntityState.Modified,
            LogType.Delete => EntityState.Deleted,
			_ => throw new ArgumentOutOfRangeException(nameof(logType), logType, null)
        };
    }
}
#endregion EntityDao<T>

#region Derived Daos
 
public partial class AlbumDao : EntityDao<Album>
{
    internal AlbumDao() {}

	protected override Expression<Func<Album, bool>> HasSameKey(Album other)
	{
        return x => x.AlbumId == other.AlbumId ;
	}

	
	private IQueryable<Album> GetByArtistIdCore(DbContext context, int artistId)
    {
        return context.Set<Album>().Where(x => x.ArtistId == artistId);
    }
	
}

 
public partial class ArtistDao : EntityDao<Artist>
{
    internal ArtistDao() {}

	protected override Expression<Func<Artist, bool>> HasSameKey(Artist other)
	{
        return x => x.ArtistId == other.ArtistId ;
	}

	
}

 
public partial class CodeDao : EntityDao<Code>
{
    internal CodeDao() {}

	protected override Expression<Func<Code, bool>> HasSameKey(Code other)
	{
        return x => x.CodeId == other.CodeId ;
	}

	
	private IQueryable<Code> GetByCodeCategoryIdCore(DbContext context, int codeCategoryId)
    {
        return context.Set<Code>().Where(x => x.CodeCategoryId == codeCategoryId);
    }
	
}

 
public partial class CodeCategoryDao : EntityDao<CodeCategory>
{
    internal CodeCategoryDao() {}

	protected override Expression<Func<CodeCategory, bool>> HasSameKey(CodeCategory other)
	{
        return x => x.CodeCategoryId == other.CodeCategoryId ;
	}

	
}

 
public partial class CustomerDao : EntityDao<Customer>
{
    internal CustomerDao() {}

	protected override Expression<Func<Customer, bool>> HasSameKey(Customer other)
	{
        return x => x.CustomerId == other.CustomerId ;
	}

	
	private IQueryable<Customer> GetBySupportRepIdCore(DbContext context, int? supportRepId)
    {
        return context.Set<Customer>().Where(x => x.SupportRepId == supportRepId);
    }
	
}

 
public partial class DateTableDao : EntityDao<DateTable>
{
    internal DateTableDao() {}

	protected override Expression<Func<DateTable, bool>> HasSameKey(DateTable other)
	{
        return x => x.Date == other.Date ;
	}

	
}

 
public partial class EmployeeDao : EntityDao<Employee>
{
    internal EmployeeDao() {}

	protected override Expression<Func<Employee, bool>> HasSameKey(Employee other)
	{
        return x => x.EmployeeId == other.EmployeeId ;
	}

	
	private IQueryable<Employee> GetByReportsToCore(DbContext context, int? reportsTo)
    {
        return context.Set<Employee>().Where(x => x.ReportsTo == reportsTo);
    }
	
}

 
public partial class GenreDao : EntityDao<Genre>
{
    internal GenreDao() {}

	protected override Expression<Func<Genre, bool>> HasSameKey(Genre other)
	{
        return x => x.GenreId == other.GenreId ;
	}

	
}

 
public partial class InvoiceDao : EntityDao<Invoice>
{
    internal InvoiceDao() {}

	protected override Expression<Func<Invoice, bool>> HasSameKey(Invoice other)
	{
        return x => x.InvoiceId == other.InvoiceId ;
	}

	
	private IQueryable<Invoice> GetByCustomerIdCore(DbContext context, int customerId)
    {
        return context.Set<Invoice>().Where(x => x.CustomerId == customerId);
    }
	
}

 
public partial class InvoiceLineDao : EntityDao<InvoiceLine>
{
    internal InvoiceLineDao() {}

	protected override Expression<Func<InvoiceLine, bool>> HasSameKey(InvoiceLine other)
	{
        return x => x.InvoiceLineId == other.InvoiceLineId ;
	}

	
	private IQueryable<InvoiceLine> GetByInvoiceIdCore(DbContext context, int invoiceId)
    {
        return context.Set<InvoiceLine>().Where(x => x.InvoiceId == invoiceId);
    }
	
}

 
public partial class MediaTypeDao : EntityDao<MediaType>
{
    internal MediaTypeDao() {}

	protected override Expression<Func<MediaType, bool>> HasSameKey(MediaType other)
	{
        return x => x.MediaTypeId == other.MediaTypeId ;
	}

	
}

 
public partial class PlaylistDao : EntityDao<Playlist>
{
    internal PlaylistDao() {}

	protected override Expression<Func<Playlist, bool>> HasSameKey(Playlist other)
	{
        return x => x.PlaylistId == other.PlaylistId ;
	}

	
}

 
public partial class PlaylistTrackDao : EntityDao<PlaylistTrack>
{
    internal PlaylistTrackDao() {}

	protected override Expression<Func<PlaylistTrack, bool>> HasSameKey(PlaylistTrack other)
	{
        return x => x.PlaylistId == other.PlaylistId  &&x.TrackId == other.TrackId ;
	}

	
	private IQueryable<PlaylistTrack> GetByPlaylistIdCore(DbContext context, int playlistId)
    {
        return context.Set<PlaylistTrack>().Where(x => x.PlaylistId == playlistId);
    }
	
	private IQueryable<PlaylistTrack> GetByTrackIdCore(DbContext context, int trackId)
    {
        return context.Set<PlaylistTrack>().Where(x => x.TrackId == trackId);
    }
	
}

 
public partial class PlaylistTrackHistoryDao : EntityDao<PlaylistTrackHistory>
{
    internal PlaylistTrackHistoryDao() {}

	protected override Expression<Func<PlaylistTrackHistory, bool>> HasSameKey(PlaylistTrackHistory other)
	{
        return x => x.PlaylistId == other.PlaylistId  &&x.TrackId == other.TrackId  &&x.WrittenAt == other.WrittenAt ;
	}

	
	private IQueryable<PlaylistTrackHistory> GetByPlaylistIdCore(DbContext context, int playlistId)
    {
        return context.Set<PlaylistTrackHistory>().Where(x => x.PlaylistId == playlistId);
    }
	
	private IQueryable<PlaylistTrackHistory> GetByTrackIdCore(DbContext context, int trackId)
    {
        return context.Set<PlaylistTrackHistory>().Where(x => x.TrackId == trackId);
    }
	
}

 
public partial class TimeTableDao : EntityDao<TimeTable>
{
    internal TimeTableDao() {}

	protected override Expression<Func<TimeTable, bool>> HasSameKey(TimeTable other)
	{
        return x => x.Time == other.Time ;
	}

	
}

 
public partial class TrackDao : EntityDao<Track>
{
    internal TrackDao() {}

	protected override Expression<Func<Track, bool>> HasSameKey(Track other)
	{
        return x => x.TrackId == other.TrackId ;
	}

	
	private IQueryable<Track> GetByAlbumIdCore(DbContext context, int? albumId)
    {
        return context.Set<Track>().Where(x => x.AlbumId == albumId);
    }
	
	private IQueryable<Track> GetByGenreIdCore(DbContext context, int genreId)
    {
        return context.Set<Track>().Where(x => x.GenreId == genreId);
    }
	
	private IQueryable<Track> GetByMediaTypeIdCore(DbContext context, int mediaTypeId)
    {
        return context.Set<Track>().Where(x => x.MediaTypeId == mediaTypeId);
    }
	
}


#endregion Derived Daos