// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class DateTableConfiguration : IEntityTypeConfiguration<DateTable>
    {
        public void Configure(EntityTypeBuilder<DateTable> entity)
        {
            entity.HasKey(e => e.Date);

            entity.ToTable("DateTable");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DateTable> entity);
    }
}
