// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>
    {
        public void Configure(EntityTypeBuilder<Invoice> entity)
        {
            entity.ToTable("Invoice");

            entity.Property(e => e.BillingAddress)
                .IsRequired()
                .HasMaxLength(70)
                .HasDefaultValue("");
            entity.Property(e => e.BillingCity)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.BillingCountry)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.BillingPostalCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("");
            entity.Property(e => e.BillingState)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.InvoiceDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Total).HasColumnType("numeric(10, 2)");

            entity.HasOne(d => d.Customer).WithMany(p => p.Invoices).HasForeignKey(d => d.CustomerId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Invoice> entity);
    }
}
