// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class PlaylistTrackHistoryConfiguration : IEntityTypeConfiguration<PlaylistTrackHistory>
    {
        public void Configure(EntityTypeBuilder<PlaylistTrackHistory> entity)
        {
            entity.HasKey(e => new { e.PlaylistId, e.TrackId, e.WrittenAt });

            entity.ToTable("PlaylistTrackHistory");

            entity.Property(e => e.WrittenAt).HasColumnType("datetime");
            entity.Property(e => e.Memo)
                .IsRequired()
                .HasMaxLength(120)
                .HasDefaultValue("");

            entity.HasOne(d => d.PlaylistTrack).WithMany(p => p.PlaylistTrackHistories)
                .HasForeignKey(d => new { d.PlaylistId, d.TrackId })
                .HasConstraintName("FK_PlaylistTrackHistory_PlaylistTrack");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlaylistTrackHistory> entity);
    }
}
