// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class TimeTableConfiguration : IEntityTypeConfiguration<TimeTable>
    {
        public void Configure(EntityTypeBuilder<TimeTable> entity)
        {
            entity.HasKey(e => e.Time);

            entity.ToTable("TimeTable");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TimeTable> entity);
    }
}
