// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class CodeConfiguration : IEntityTypeConfiguration<Code>
    {
        public void Configure(EntityTypeBuilder<Code> entity)
        {
            entity.ToTable("Code");

            entity.Property(e => e.CodeId).ValueGeneratedNever();
            entity.Property(e => e.Memo)
                .IsRequired()
                .HasMaxLength(1000)
                .HasDefaultValue("");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("");

            entity.HasOne(d => d.CodeCategory).WithMany(p => p.Codes).HasForeignKey(d => d.CodeCategoryId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Code> entity);
    }
}
