// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> entity)
        {
            entity.ToTable("Customer");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(70)
                .HasDefaultValue("");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.Company)
                .IsRequired()
                .HasMaxLength(80)
                .HasDefaultValue("");
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60)
                .HasDefaultValue("");
            entity.Property(e => e.Fax)
                .IsRequired()
                .HasMaxLength(24)
                .HasDefaultValue("");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(24)
                .HasDefaultValue("");
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("");
            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");

            entity.HasOne(d => d.SupportRep).WithMany(p => p.Customers).HasForeignKey(d => d.SupportRepId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customer> entity);
    }
}
