// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Chinook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Chinook.Data.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.ToTable("Employee");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(70)
                .HasDefaultValue("");
            entity.Property(e => e.BirthDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(60)
                .HasDefaultValue("");
            entity.Property(e => e.Fax)
                .IsRequired()
                .HasMaxLength(24)
                .HasDefaultValue("");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("");
            entity.Property(e => e.HireDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(24)
                .HasDefaultValue("");
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("");
            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(40)
                .HasDefaultValue("");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("");

            entity.HasOne(d => d.ReportsToNavigation).WithMany(p => p.InverseReportsToNavigation).HasForeignKey(d => d.ReportsTo);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
