// <auto-generated> This file has been generated by Gccg</auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion
namespace Chinook.Data;


public class CodeMetaData
{
    
	public int CodeId {get; set;}

	public int CodeCategoryId {get; set;}

	public string Memo {get; set;}

	public string Text {get; set;}
} 

