// <auto-generated> This file has been generated by Gccg</auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace Chinook.Data;


public class InvoiceLineMetaData
{
    
	public int InvoiceLineId {get; set;}

	public int InvoiceId {get; set;}

	public int Quantity {get; set;}

	public int TrackId {get; set;}

	public decimal UnitPrice {get; set;}
} 
