// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chinook.Data;

public partial class CodeCategory
{
    public int CodeCategoryId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Code> Codes { get; set; } = new List<Code>();
}