
// This file has been generated by Gccg on 2024-04-24 오후 7:12:53.
#region using
using System.Collections.Generic;
using System.Linq;
#endregion

namespace Chinook.Data;


public partial class CodeCategoryDao
{
}

