
// This file has been generated by Gccg on 2024-01-28 오후 2:02:37.
#region using
using System.Collections.Generic;
using System.Linq;
#endregion

namespace Chinook.Data;


public partial class DateTableDao
{
}

