// <auto-generated> This file has been auto generated at 2024-04-25 오후 6:33:46 </auto-generated>

namespace Chinook.Data;

public partial class Genre
{
    public const int _1_Pop = 1;
public const int _2_Ballad = 2;
public const int _3_RockRoll = 3;

}