
// This file has been generated by Gccg on 2024-04-24 오후 7:12:53.
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace Chinook.Data;


#region CodeCategoryMetadata
public class CodeCategoryMetaData
{
    public int CodeCategoryId {get; set;} 
		public string Name {get; set;} 
}
#endregion

[MetadataType(typeof(CodeCategoryMetaData))]
public partial class CodeCategory
{
}

