
// This file has been generated by Gccg on 2024-01-28 오후 2:02:37.
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace Chinook.Data;


#region DateTableMetadata
public class DateTableMetaData
{
    public DateOnly Date {get; set;} 
		public DateOnly DateNull {get; set;} 
}
#endregion

[MetadataType(typeof(DateTableMetaData))]
public partial class DateTable
{
}

