// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chinook.Data;

public partial class Artist
{
    public int ArtistId { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// [1]
    /// </summary>
    public int TypeCode { get; set; }

    public virtual ICollection<Album> Albums { get; set; } = new List<Album>();
}