// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chinook.Data;

public partial class DateTable
{
    public DateOnly Date { get; set; }

    public DateOnly? DateNull { get; set; }
}