// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chinook.Data;

public partial class TimeTable
{
    public TimeOnly Time { get; set; }

    public TimeOnly? TimeNull { get; set; }
}